name: nginx-proxy

networks:
  kafka-network:
    external: true

volumes:
  shared-volume:
    external: true

services:
  nginx-proxy:
    image: nginx-proxy:latest
    container_name: nginx-proxy
    build:
      context: .
      dockerfile: ./nginx.dockerfile
    ports:
      - 443:443
    networks:
      - kafka-network
    volumes:
      - shared-volume:/usr/app/ssl:rw
