name: nginx-proxy

networks:
  kafka-network:
    external: true

volumes:
  shared-volume:
    external: true

services:
  nginx-proxy:
    image: nginx-proxy:latest
    container_name: nginx-proxy
    build:
      context: .
      dockerfile: ./nginx.dockerfile
    ports:
      - 443:443
    networks:
      - kafka-network
    volumes:
      - shared-volume:/usr/app/ssl:rw
  mongo-express:
    image: mongo-express
    environment:
      - ME_CONFIG_MONGODB_SERVER=nextgen-mongo
      - ME_CONFIG_MONGODB_PORT=27000
      - ME_CONFIG_MONGODB_ADMINUSERNAME=yogeshs
      - ME_CONFIG_MONGODB_ADMINPASSWORD=dezireGadi7081
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=false
      - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
      - ME_CONFIG_MONGODB_AUTH_USERNAME=yogeshs
      - ME_CONFIG_MONGODB_AUTH_PASSWORD=dezireGadi7081
      - ME_CONFIG_BASICAUTH_USERNAME=yogeshs
      - ME_CONFIG_BASICAUTH_PASSWORD=yogeshs8032
    depends_on:
      - nextgen-mongo
    ports:
      - 8081:8081
    networks:
      - nextgen-network