name: nextgen-apps

networks:
  nextgen-network:
    external: true

services:
  nextgen-mongo:
    image: nextgen-mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=yogeshs
      - MONGO_INITDB_ROOT_PASSWORD=dezireGadi7081
      - MONGO_INITDB_DATABASE=sonawaneyogeshb
    networks:
      - nextgen-network
    ports:
      - 27000:27000
  nextgen-server:
    image: nextgen-server:latest
    container_name: nextgen-server
    hostname: nextgen-server
    build:
      context: .
      dockerfile: ./dockerfile
    environment:
      NODE_ENV: production
      NG_MONGO_HOST: nextgen-mongo
      NG_MONGO_USER: yogeshs
      NG_MONGO_PASS: dezireGadi7081
      NG_MONGO_DB: sonawaneyogeshb
      NG_MONGO_PORT: 27000
    env_file:
      - .env  
    ports:
      - 9000:9000
      - 9229:9229
    depends_on:
      - nextgen-mongo
    networks:
      - nextgen-network
  flokapture-nextgen:
    image: flokapture-nextgen:latest
    container_name: flokapture-nextgen
    hostname: flokapture-nextgen
    build:
      context: .
      dockerfile: ./dockerfile
    environment:
      NODE_ENV: production
      NG_MONGO_HOST: nextgen-mongo
      NG_MONGO_USER: yogeshs
      NG_MONGO_PASS: dezireGadi7081
      NG_MONGO_DB: sonawaneyogeshb
      NG_MONGO_PORT: 27000
    env_file:
      - .env
    depends_on:
      - nextgen-mongo
      - nextgen-server    
    ports:
      - 3000:3000
      - 9222:9222    
    networks:
      - nextgen-network    