name: next-gen-server

networks:
  next-gen-network:
    external: true

services:
  next-gen-server:
    image: next-gen-server:latest
    container_name: next-gen-server
    hostname: next-gen-server
    build:
      context: .
      dockerfile: ./dockerfile
    environment:
      NODE_ENV: production
    env_file:
      - .env  
    ports:
      - 9000:9000
      - 9229:9229    
    networks:
      - next-gen-network
    develop:
      watch:
        - path: /src
          target: /app/src
          action: sync
          ignore:
            - "node_modules/"
            - "Jenkinsfile"
            - "Jenkins.Dockerfile"
            - "*.md"
            - "*.dockerfile"  