apiVersion: v1
kind: Service
metadata:
  annotations:
    compose.cmd: docker-compose-services
    compose.version: 1.31.2
  labels:
    io.compose.service: control-center
  name: control-center
spec:
  ports:
    - name: "9021"
      port: 9021
      targetPort: 9021
  selector:
    io.compose.service: control-center
status:
  loadBalancer: {}
