apiVersion: v1
kind: Service
metadata:
  name: flou-job-api
spec:
  selector:
    io.compose.service: flou-job-api
  ports:
    - protocol: TCP
      port: 3800
      targetPort: 3800
  type: ClusterIP