apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    compose.cmd: docker-compose-services
    compose.version: 1.31.2
  labels:
    io.compose.service: kafka
  name: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      io.compose.service: kafka
  strategy: {}
  template:
    metadata:
      annotations:
        compose.cmd: docker-compose-services
        compose.version: 1.31.2
      labels:
        network/kafka-network: "true"
        io.compose.service: kafka
    spec:
      containers:
        - env:
            - name: ALLOW_PLAINTEXT_LISTENER
              value: "yes"
            - name: AUTO_CREATE_TOPICS_ENABLE
              value: "true"
            - name: CONFLUENT_METRICS_ENABLE
              value: "true"
            - name: CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS
              value: kafka:9092
            - name: CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS
              value: "1"
            - name: CONFLUENT_SUPPORT_CUSTOMER_ID
              value: anonymous
            - name: KAFKA_ADVERTISED_LISTENERS
              value: PLAINTEXT://kafka:9092,INSIDE://127.0.0.1:9099,OUTSIDE://127.0.0.1:9094
            - name: KAFKA_BROKER_ID
              value: "1"
            - name: KAFKA_CONFLUENT_BALANCER_TOPIC_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_CONFLUENT_SCHEMA_REGISTRY_URL
              value: http://schema-registry:8081
            - name: KAFKA_GROUP_ID
              value: kafka
            - name: KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS
              value: "0"
            - name: KAFKA_JMX_HOSTNAME
              value: localhost
            - name: KAFKA_JMX_PORT
              value: "9101"
            - name: KAFKA_LISTENERS
              value: PLAINTEXT://0.0.0.0:9092,INSIDE://127.0.0.1:9099,OUTSIDE://127.0.0.1:9094
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT,PLAINTEXT:PLAINTEXT
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
              value: "1"
            - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: zookeeper:2181
            - name: LOG4J_LOGGER_IO_CONFLUENT_METRICS_REPORTER_CONFLUENT_METRICS_REPORTER
              value: DEBUG
            - name: METRIC_REPORTERS
              value: io.confluent.metrics.reporter.ConfluentMetricsReporter
          image: confluentinc/cp-kafka:latest
          name: flou-kafka
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9092
              hostPort: 9092
              protocol: TCP
            - containerPort: 9099
              hostPort: 9099
              protocol: TCP
            - containerPort: 9094
              hostPort: 9094
              protocol: TCP
          readinessProbe:
            tcpSocket:
              port: 9092
            initialDelaySeconds: 5
            periodSeconds: 10    
          resources:
            limits:
              cpu: "1"
              memory: "1Gi"
            requests:
              cpu: "0.5"
              memory: "512Mi"
      restartPolicy: Always
status: {}
