apiVersion: v1
kind: Service
metadata:
  annotations:
    compose.cmd: docker-compose-services
    compose.version: 1.31.2
  labels:
    io.compose.service: zookeeper
  name: zookeeper
spec:
  ports:
    - name: "2181"
      port: 2181
      targetPort: 2181
  selector:
    io.compose.service: zookeeper
status:
  loadBalancer: {}
