apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    compose.cmd: docker-compose-services
    compose.version: 1.31.2
  labels:
    io.compose.service: zookeeper
  name: zookeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      io.compose.service: zookeeper
  strategy: {}
  template:
    metadata:
      annotations:
        compose.cmd: docker-compose-services
        compose.version: 1.31.2
      labels:
        io.compose.network/kafka-network: "true"
        io.compose.service: zookeeper
    spec:
      containers:
        - env:
            - name: ZOOKEEPER_CLIENT_PORT
              value: "2181"
            - name: ZOOKEEPER_TICK_TIME
              value: "2000"
          image: confluentinc/cp-zookeeper:latest
          name: flou-zookeeper
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 2181
              hostPort: 2181
              protocol: TCP
          resources:
            limits:
              cpu: "0.5"
              memory: "512Mi"
            requests:
              cpu: "0.1"
              memory: "256Mi"
      restartPolicy: Always
status: {}
